### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by JasonKeirstead** [alexkuz/flask-react-boilerplate#4]
FYI I have not been able to get this to deploy, either locally or on Heroku

Here is the error log from Heroku but I get a simmilar error locally.

 make: Entering directory `/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
       CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
       SOLINK_MODULE(target) Release/obj.target/bufferutil.node
       SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
       COPY Release/bufferutil.node
       make: Leaving directory`/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'

```
   > utf-8-validate@1.2.1 install /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
   > node-gyp rebuild

   make: Entering directory `/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
   CXX(target) Release/obj.target/validation/src/validation.o
   SOLINK_MODULE(target) Release/obj.target/validation.node
   SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
   COPY Release/validation.node
   make: Leaving directory `/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'

   > bufferutil@1.2.1 install /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
   > node-gyp rebuild

   make: Entering directory `/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
   SOLINK_MODULE(target) Release/obj.target/bufferutil.node
   SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
   COPY Release/bufferutil.node
   make: Leaving directory `/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack-dev-server/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'

   > contextify@0.1.15 install /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
   > node-gyp rebuild

   make: Entering directory `/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/build'
   CXX(target) Release/obj.target/contextify/src/contextify.o
   SOLINK_MODULE(target) Release/obj.target/contextify.node
   SOLINK_MODULE(target) Release/obj.target/contextify.node: Finished
   COPY Release/contextify.node
   make: Leaving directory `/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify/build'

   > flask-react-boilerplate@0.0.1 postinstall /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74
   > npm run dist


   > flask-react-boilerplate@0.0.1 dist /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74
   > NODE_ENV=production webpack -p

   ModuleBuildError: Module build failed: /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/eslint-loader/index.js!/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/client/flux/kittens.js: Maximum call stack size exceeded
   at DependenciesBlock.onModuleBuildFailed (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
   at nextLoader (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
   at /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
   at runSyncOrAsync (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
   at nextLoader (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
   at /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
   at context.callback (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
   at lint (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/eslint-loader/index.js:64:5)
   at Object.module.exports (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/eslint-loader/index.js:97:7)
   at WEBPACK_CORE_LOADER_EXECUTION (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
   at runSyncOrAsync (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
   at nextLoader (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
   at /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
   at Storage.finished (/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
   at evalmachine.<anonymous>:272:14
   at /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:102:5

   npm ERR! Linux 3.13.0-66-generic
   npm ERR! argv "node" "/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/.heroku/node/bin/npm" "run" "dist"
   npm ERR! node v0.10.40
   npm ERR! npm  v2.10.1
   npm ERR! code ELIFECYCLE
   npm ERR! flask-react-boilerplate@0.0.1 dist: `NODE_ENV=production webpack -p`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the flask-react-boilerplate@0.0.1 dist script 'NODE_ENV=production webpack -p'.
   npm ERR! This is most likely a problem with the flask-react-boilerplate package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     NODE_ENV=production webpack -p
   npm ERR! You can get their info via:
   npm ERR!     npm owner ls flask-react-boilerplate
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/npm-debug.log

   npm ERR! Linux 3.13.0-66-generic
   npm ERR! argv "node" "/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/.npmrc"
   npm ERR! node v0.10.40
   npm ERR! npm  v2.10.1
   npm ERR! code ELIFECYCLE
   npm ERR! flask-react-boilerplate@0.0.1 postinstall: `npm run dist`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the flask-react-boilerplate@0.0.1 postinstall script 'npm run dist'.
   npm ERR! This is most likely a problem with the flask-react-boilerplate package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     npm run dist
   npm ERR! You can get their info via:
   npm ERR!     npm owner ls flask-react-boilerplate
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /tmp/build_c9226506c198be2d94b78c69bb8bc03e/alexkuz-flask-react-boilerplate-7d2cc74/npm-debug.log
```

-----> Build failed

```
   We're sorry this build is failing! You can troubleshoot common issues here:
   https://devcenter.heroku.com/articles/troubleshooting-node-deploys

   If you're stuck, please submit a ticket so we can help:
   https://help.heroku.com/

   Love,
   Heroku
```

 !     Push rejected, failed to compile Multipack app

**Comment by alexkuz** [comment]
Thanks! I'll have a look later (and it should be updated and migrated to redux anyway)

**Comment by alexkuz** [comment]
It should work now.
