### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by alaneng-zz** [alexkuz/flask-react-boilerplate#5]
Hi, this might be an issue with some libraries having been deprecated, but I'm getting an issue with the `npm install` step. I cloned the repo, cd into it, and running `npm install` produces the following error:

> flask-react-boilerplate@0.0.1 dist /Users/alaneng/Documents/code/alaneng.github.io/flask-react-boilerplate
> NODE_ENV=production webpack -p
> ModuleBuildError: Module build failed: RangeError: /Users/alaneng/Documents/code/alaneng.github.io/flask-react-boilerplate/node_modules/eslint-loader/index.js!/Users/alaneng/Documents/code/alaneng.github.io/flask-react-boilerplate/client/flux/kittens.js: Maximum call stack size exceeded
>     at hasOwnProperty (native)
>     at Function.Def.fromValue (/Users/alaneng/Documents/code/alaneng.github.io/flask-react-boilerplate/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:305:20)

It says to indicate this failed on my system:
`NODE_ENV=production webpack -p`

Here's the npm-debug.log:
[npm-debug.txt](https://github.com/alexkuz/flask-react-boilerplate/files/77693/npm-debug.txt)

Thanks!!

**Comment by typpo** [comment]
Having this problem as well.  

```
ModuleBuildError: Module build failed: RangeError: /.../node_modules/eslint-loader/index.js!/.../client/flux/kittens.js: Maximum call stack size exceeded
at String.toString (native)
at Type.<anonymous> (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:94:25)
at Type.Object.defineProperties.check.value (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:37:36)
at Field.Fp.getValue (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:251:22)
at Object.getFieldValue (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/types.js:676:26)
at NodePath.NPp.getValueProperty (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/node-path.js:123:18)
at getChildPath (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:50:33)
at NodePath.get (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:74:16)
at visitChildren (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:240:34)
at Visitor.PVp.visitWithoutReset (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:202:16)
at visitChildren (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:244:21)
at Visitor.PVp.visitWithoutReset (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:202:16)
at NodePath.each (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path.js:99:22)
at visitChildren (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:217:14)
at Visitor.PVp.visitWithoutReset (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:202:16)
at visitChildren (/home/ian/code/astrokit/web/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:244:21)
at DependenciesBlock.onModuleBuildFailed (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
at nextLoader (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
at /home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
at runSyncOrAsync (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
at nextLoader (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
at /home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
at context.callback (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
at lint (/home/ian/code/astrokit/web/node_modules/eslint-loader/index.js:64:5)
at Object.module.exports (/home/ian/code/astrokit/web/node_modules/eslint-loader/index.js:97:7)
at WEBPACK_CORE_LOADER_EXECUTION (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
at runSyncOrAsync (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
at nextLoader (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
at /home/ian/code/astrokit/web/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
at Storage.finished (/home/ian/code/astrokit/web/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
at evalmachine.<anonymous>:334:14
at /home/ian/code/astrokit/web/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:102:5
```

**Comment by alexkuz** [comment]
Thanks! I've promised to look at it couple of months ago and totally forgot (https://github.com/alexkuz/flask-react-boilerplate/issues/4), shame on me :(

**Comment by alexkuz** [comment]
I've updated this, try it out.
